### 회원가입
POST {{BASE_URL}}/api/v1/users/signup
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "nickname": "관주",
  "university": "AJOU",
  "collegeName": "소프트웨어융합대학",
  "department": "소프트웨어학과",
  "degree": "BACHELOR",
  "schoolEmail": "kkj6235@ajou.ac.kr",
  "marketingConsent" : true
}

### 설정 상태 조회
GET {{BASE_URL}}/api/v1/users/settings/NOTIFICATION
Authorization: Bearer {{ACCESS_TOKEN}}


### 설정 상태 토글
PATCH {{BASE_URL}}/api/v1/users/settings/NOTIFICATION
Authorization: Bearer {{ACCESS_TOKEN}}
