### 목록 검색 : 알림
GET {{BASE_URL}}/api/v1/notifications?notificationType=KEYWORD
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 읽음 상태 변경 : 알림
PATCH {{BASE_URL}}/api/v1/notifications/48/read
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 읽음 상태 변경 : 알림
PATCH {{BASE_URL}}/api/v1/notifications/read
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "notificationType": "KEYWORD",
  "entityType": "NOTICE",
  "entityId": "hzLw_ZQBnS9loj4r4-mF"
}

### 읽음 상태 변경 : 알림
POST {{BASE_URL}}/api/v1/notifications/send
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title" : "[장학금 사이트 업데이트]",
  "content" : "장학금 게시판을 확인해주세요!",
    "deviceTokens": [""]
}




