### 생성 : 키워드
POST {{BASE_URL}}/api/v1/keywords
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "text": "등록금"
}

### 검색 : 키워드
GET {{BASE_URL}}/api/v1/keywords
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 삭제 : 키워드
DELETE {{BASE_URL}}/api/v1/keywords/2
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json
