### 로그인: 인증
POST {{BASE_URL}}/api/v1/auth/login
Content-Type: application/json

{
  "provider": "GOOGLE",
  "oauthToken": "mock-1234-5678"
}

### 게스트 로그인: 인증
POST {{BASE_URL}}/api/v1/auth/guest-login

### 토큰 재 발급: 인증
POST {{BASE_URL}}/api/v1/auth/refresh
Content-Type: application/json

{
  "token": "mock-1234-5678"
}

### 이메일 인증번호 요청: 인증
POST {{BASE_URL}}/api/v1/auth/email
Content-Type: application/json

{
  "university": "AJOU",
  "email": "kkj6235@ajou.ac.kr"
}



