### 생성 : 리액션
PUT {{BASE_URL}}/api/v1/reactions
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "targetType": "NOTICE",
  "targetId": "bTKu7ZQBnS9loj4rsukq",
  "type": "SCRAP"
}