### 검색 : 즐겨찾기
GET {{BASE_URL}}/api/v1/notices/bookmarks
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 업데이트 : 즐겨찾기
PATCH {{BASE_URL}}/api/v1/notices/bookmarks
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "sources" : [
      "ACADEMIC_NOTICE", "RC_EDUCATION"
  ]
}

