### 검색 : 공지사항
GET {{BASE_URL}}/api/v1/notices
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json


### 조회 : 공지사항
GET {{BASE_URL}}/api/v1/notices/fGhOO5QBORDZUx8puAN_
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 반응한 공지사항 검색 : 공지사항
GET {{BASE_URL}}/api/v1/notices/me/reactions?reactionType=SCRAP
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json
